server:
  port: ${PORT:80}
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:rick}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect